from __future__ import annotations

from importlib import import_module
from typing import Any

from ._version import __version__
from .capabilities import CAPABILITY_MATRIX, list_capabilities
from .client import AntibotClient, SolveResult
from .models import (
    BatchItemResult,
    BatchResult,
    BrowserResult,
    CaptchaResult,
    SolveRequest,
)
from .policy import AliyunPolicyEngine, PolicyDecision, aliyun_policy_decision
from .profiles import AliyunSiteProfile, aliyun_profile_for_url, detect_provider_for_url, list_profiles
from .proxy import (
    LocalAnonymizedProxy,
    ProxyConfig,
    chromium_proxy_server,
    env_proxy_candidates,
    normalize_proxy_server,
    normalize_proxy_url,
    parse_proxy,
    prepare_chromium_proxy,
    proxy_free_environment,
    redacted_proxy,
    resolve_runtime_proxy,
)
from .runtime import runtime_diagnostics
from .stress import compact_result, run_stress

_LAZY_EXPORTS = {
    "ALIYUN_CAPTCHA_TYPES": (".providers.aliyun", "ALIYUN_CAPTCHA_TYPES"),
    "ALIYUN_NON_PRODUCTION_VERIFY_CODES": (
        ".providers.aliyun",
        "ALIYUN_NON_PRODUCTION_VERIFY_CODES",
    ),
    "ALIYUN_PASS_VERIFY_CODES": (".providers.aliyun", "ALIYUN_PASS_VERIFY_CODES"),
    "AliyunCaptchaSolver": (".providers.aliyun", "AliyunCaptchaSolver"),
    "BrowserAutomation": (".providers.browser", "BrowserAutomation"),
    "CaptchaWidgetSolver": (".providers.widgets", "CaptchaWidgetSolver"),
    "ArkoseCaptchaSolver": (".providers.arkose", "ArkoseCaptchaSolver"),
    "ArkoseChallengeSession": (".providers.arkose", "ArkoseChallengeSession"),
    "RecaptchaChallengeSession": (
        ".providers.widgets",
        "RecaptchaChallengeSession",
    ),
    "TurnstileChallengeSession": (
        ".providers.turnstile",
        "TurnstileChallengeSession",
    ),
    "TencentChallengeSession": (
        ".providers.tencent_session",
        "TencentChallengeSession",
    ),
    "TencentSliderChallengeSession": (
        ".providers.tencent_session",
        "TencentSliderChallengeSession",
    ),
    "TencentWordOCRBackend": (
        ".providers.tencent_session",
        "TencentWordOCRBackend",
    ),
    "CaptchaHarness": (".harness", "CaptchaHarness"),
    "TokenChallengeSession": (".harness", "TokenChallengeSession"),
    "BrowserChallengeSession": (".harness", "BrowserChallengeSession"),
    "ActionPlanningBackend": (".harness", "ActionPlanningBackend"),
    "ActionSolveOutcome": (".harness", "ActionSolveOutcome"),
    "StaticActionPlanningBackend": (".harness", "StaticActionPlanningBackend"),
    "OpenAICompatibleActionPlanningBackend": (
        ".harness",
        "OpenAICompatibleActionPlanningBackend",
    ),
    "ActionValidation": (".harness", "ActionValidation"),
    "ChallengeAgentLoop": (".harness", "ChallengeAgentLoop"),
    "ChallengeActionRejected": (".harness", "ChallengeActionRejected"),
    "ChallengeExecutor": (".harness", "ChallengeExecutor"),
    "ChallengeLoopResult": (".harness", "ChallengeLoopResult"),
    "ChallengeSession": (".harness", "ChallengeSession"),
    "ChallengeStrategyRegistry": (".harness", "ChallengeStrategyRegistry"),
    "CoverageAssessment": (".harness", "CoverageAssessment"),
    "CoveragePolicy": (".harness", "CoveragePolicy"),
    "BenchmarkAssessment": (".harness", "BenchmarkAssessment"),
    "BenchmarkPolicy": (".harness", "BenchmarkPolicy"),
    "ChallengeAction": (".harness", "ChallengeAction"),
    "ChallengeAffordance": (".harness", "ChallengeAffordance"),
    "ChallengeCandidate": (".harness", "ChallengeCandidate"),
    "ChallengeObservation": (".harness", "ChallengeObservation"),
    "DEFAULT_GEETEST_DEMO_URL": (".providers.geetest", "DEFAULT_GEETEST_DEMO_URL"),
    "DEFAULT_GEETEST_GOBANG_DEMO_URL": (
        ".providers.geetest",
        "DEFAULT_GEETEST_GOBANG_DEMO_URL",
    ),
    "DEFAULT_GEETEST_SLIDE_DEMO_URL": (
        ".providers.geetest",
        "DEFAULT_GEETEST_SLIDE_DEMO_URL",
    ),
    "GeetestV4ParseError": (".providers.geetest", "GeetestV4ParseError"),
    "GeetestV4Solver": (".providers.geetest", "GeetestV4Solver"),
    "RunnerConfig": (".providers.cloudflare", "RunnerConfig"),
    "RunResult": (".providers.cloudflare", "RunResult"),
    "ServiceSettings": (".service", "ServiceSettings"),
    "TencentCaptchaSolver": (".providers.tencent", "TencentCaptchaSolver"),
    "OpenAICompatibleVisionBackend": (
        ".vision",
        "OpenAICompatibleVisionBackend",
    ),
    "HarnessBudget": (".harness", "HarnessBudget"),
    "HarnessDecision": (".harness", "HarnessDecision"),
    "HarnessEvidence": (".harness", "HarnessEvidence"),
    "HarnessPlanner": (".harness", "HarnessPlanner"),
    "HarnessState": (".harness", "HarnessState"),
    "HarnessTool": (".harness", "HarnessTool"),
    "HarnessToolRegistry": (".harness", "HarnessToolRegistry"),
    "HeuristicPlanner": (".harness", "HeuristicPlanner"),
    "PydanticAIPlanner": (".harness", "PydanticAIPlanner"),
    "ProviderAdapter": (".harness", "ProviderAdapter"),
    "ProviderAdapterRegistry": (".harness", "ProviderAdapterRegistry"),
    "ReplayReport": (".harness", "ReplayReport"),
    "ReplayRun": (".harness", "ReplayRun"),
    "evaluate_replays": (".harness", "evaluate_replays"),
    "StaticVisionBackend": (".vision", "StaticVisionBackend"),
    "VisionAnswer": (".vision", "VisionAnswer"),
    "VisionBackend": (".vision", "VisionBackend"),
    "VisionBackendError": (".vision", "VisionBackendError"),
    "VisionImage": (".vision", "VisionImage"),
    "VisionSolveOutcome": (".vision", "VisionSolveOutcome"),
    "VisionSolvePolicy": (".vision", "VisionSolvePolicy"),
    "VisionChallengePolicy": (".harness", "VisionChallengePolicy"),
    "VisionTask": (".vision", "VisionTask"),
    "detect_geetest_slide_gap": (".providers.geetest", "detect_geetest_slide_gap"),
    "detect_widget_provider": (".providers.widgets", "detect_widget_provider"),
    "detect_arkose_provider": (".providers.arkose", "detect_arkose_provider"),
    "diagnose_environment": (".providers.cloudflare", "diagnose_environment"),
    "discover_chrome": (".providers.aliyun", "discover_chrome"),
    "find_geetest_match_swap": (".providers.geetest", "find_geetest_match_swap"),
    "find_geetest_winlinze_move": (".providers.geetest", "find_geetest_winlinze_move"),
    "geetest_query": (".providers.geetest", "geetest_query"),
    "geetest_v4_success_from_events": (
        ".providers.geetest",
        "geetest_v4_success_from_events",
    ),
    "is_geetest_success_payload": (".providers.geetest", "is_geetest_success_payload"),
    "is_recoverable_attempt_codes": (".providers.aliyun", "is_recoverable_attempt_codes"),
    "aliyun_verify_passed": (".providers.aliyun", "aliyun_verify_passed"),
    "normalize_aliyun_captcha_type": (
        ".providers.aliyun",
        "normalize_aliyun_captcha_type",
    ),
    "latest_geetest_success": (".providers.geetest", "latest_geetest_success"),
    "normalize_geetest_variant": (".providers.geetest", "normalize_geetest_variant"),
    "normalize_widget_provider": (".providers.widgets", "normalize_widget_provider"),
    "normalize_arkose_provider": (".providers.arkose", "normalize_arkose_provider"),
    "parse_geetest_jsonp": (".providers.geetest", "parse_geetest_jsonp"),
    "parse_geetest_v4_event": (".providers.geetest", "parse_geetest_v4_event"),
    "run_once": (".providers.cloudflare", "run_once"),
    "create_app": (".service", "create_app"),
}


def __getattr__(name: str) -> Any:
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = target
    value = getattr(import_module(module_name, __name__), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS))

__all__ = [
    "ALIYUN_CAPTCHA_TYPES",
    "ALIYUN_NON_PRODUCTION_VERIFY_CODES",
    "ALIYUN_PASS_VERIFY_CODES",
    "AliyunCaptchaSolver",
    "AliyunPolicyEngine",
    "AliyunSiteProfile",
    "AntibotClient",
    "BrowserAutomation",
    "BrowserResult",
    "BatchItemResult",
    "BatchResult",
    "CAPABILITY_MATRIX",
    "CaptchaResult",
    "CaptchaWidgetSolver",
    "ArkoseCaptchaSolver",
    "ArkoseChallengeSession",
    "RecaptchaChallengeSession",
    "TurnstileChallengeSession",
    "TencentChallengeSession",
    "TencentSliderChallengeSession",
    "TencentWordOCRBackend",
    "CaptchaHarness",
    "TokenChallengeSession",
    "BrowserChallengeSession",
    "ActionPlanningBackend",
    "ActionSolveOutcome",
    "StaticActionPlanningBackend",
    "OpenAICompatibleActionPlanningBackend",
    "ActionValidation",
    "ChallengeAgentLoop",
    "ChallengeActionRejected",
    "ChallengeExecutor",
    "ChallengeLoopResult",
    "ChallengeSession",
    "ChallengeStrategyRegistry",
    "CoverageAssessment",
    "CoveragePolicy",
    "BenchmarkAssessment",
    "BenchmarkPolicy",
    "ChallengeAction",
    "ChallengeAffordance",
    "ChallengeCandidate",
    "ChallengeObservation",
    "SolveRequest",
    "SolveResult",
    "DEFAULT_GEETEST_DEMO_URL",
    "DEFAULT_GEETEST_SLIDE_DEMO_URL",
    "DEFAULT_GEETEST_GOBANG_DEMO_URL",
    "GeetestV4ParseError",
    "GeetestV4Solver",
    "HarnessBudget",
    "HarnessDecision",
    "HarnessEvidence",
    "HarnessPlanner",
    "HarnessState",
    "HarnessTool",
    "HarnessToolRegistry",
    "HeuristicPlanner",
    "detect_geetest_slide_gap",
    "detect_widget_provider",
    "detect_arkose_provider",
    "find_geetest_match_swap",
    "find_geetest_winlinze_move",
    "PolicyDecision",
    "LocalAnonymizedProxy",
    "ProxyConfig",
    "PydanticAIPlanner",
    "ProviderAdapter",
    "ProviderAdapterRegistry",
    "ReplayReport",
    "ReplayRun",
    "RunnerConfig",
    "RunResult",
    "ServiceSettings",
    "TencentCaptchaSolver",
    "OpenAICompatibleVisionBackend",
    "StaticVisionBackend",
    "VisionAnswer",
    "VisionBackend",
    "VisionBackendError",
    "VisionImage",
    "VisionSolveOutcome",
    "VisionSolvePolicy",
    "VisionChallengePolicy",
    "VisionTask",
    "aliyun_policy_decision",
    "aliyun_verify_passed",
    "aliyun_profile_for_url",
    "compact_result",
    "create_app",
    "detect_provider_for_url",
    "diagnose_environment",
    "discover_chrome",
    "geetest_query",
    "geetest_v4_success_from_events",
    "is_geetest_success_payload",
    "normalize_geetest_variant",
    "normalize_aliyun_captcha_type",
    "normalize_widget_provider",
    "normalize_arkose_provider",
    "latest_geetest_success",
    "is_recoverable_attempt_codes",
    "list_capabilities",
    "list_profiles",
    "chromium_proxy_server",
    "env_proxy_candidates",
    "evaluate_replays",
    "normalize_proxy_server",
    "normalize_proxy_url",
    "parse_geetest_jsonp",
    "parse_geetest_v4_event",
    "parse_proxy",
    "prepare_chromium_proxy",
    "proxy_free_environment",
    "redacted_proxy",
    "resolve_runtime_proxy",
    "runtime_diagnostics",
    "run_once",
    "run_stress",
    "__version__",
]
