from __future__ import annotations

from copy import deepcopy
from typing import Any


CAPABILITY_MATRIX: dict[str, dict[str, Any]] = {
    "tencent": {
        "provider": "tencent",
        "name": "Tencent Captcha",
        "category": "solver",
        "captcha_type": "slider",
        "status": "primary",
        "output": "ticket/randstr",
        "scope": "腾讯滑块：缺口识别 + 轨迹拖拽 + ticket/randstr 提取。",
    },
    "aliyun": {
        "provider": "aliyun",
        "name": "Aliyun Captcha",
        "category": "solver",
        "captcha_type": "slider",
        "status": "primary",
        "output": "verify_code/session artifacts",
        "scope": "阿里云滑块：站点 profile + CV 缺口 + 轨迹拖拽 + attempt/session retry。",
    },
    "ajcaptcha": {
        "provider": "ajcaptcha",
        "name": "AJ-Captcha / Anji",
        "category": "solver",
        "captcha_type": "slider_protocol",
        "status": "alpha",
        "output": "captchaVerification/token",
        "scope": "AJ-Captcha blockPuzzle：/captcha/get 图像缺口定位 + AES pointJson + /captcha/check 协议提交；不启动浏览器。",
    },
    "altcha": {
        "provider": "altcha",
        "name": "ALTCHA",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "base64 payload / Authorization header",
        "scope": "ALTCHA v1 PoW：解析 challenge 或 WWW-Authenticate，计算 number，输出表单 payload 或 M2M Authorization header；不启动浏览器。",
    },
    "anubis": {
        "provider": "anubis",
        "name": "Anubis",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "pass-challenge params / auth cookie",
        "scope": "Anubis fast/slow PoW：解析页面或 make-challenge JSON，计算 SHA256(randomData+nonce) 前导零，生成 pass-challenge 参数，可提交换 cookie；不启动浏览器。",
    },
    "auro": {
        "provider": "auro",
        "name": "Auro.Network",
        "category": "solver",
        "captcha_type": "encrypted_behavior_pow",
        "status": "alpha",
        "output": "validate body / Auro token",
        "scope": "Auro.Network AES-GCM 行为数据 + SHA-256 PoW：获取 enckey，生成鼠标轨迹并 AES-GCM 加密，提交 setup 拿 prefix/difficulty，搜索 nonce 后 validate；不启动浏览器。",
    },
    "friendlycaptcha": {
        "provider": "friendlycaptcha",
        "name": "FriendlyCaptcha",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "frc-captcha-solution payload",
        "scope": "FriendlyCaptcha classic PoW：获取 puzzle，按 friendly-pow/blake2b 求解多段 nonce，输出隐藏表单字段 payload；不启动浏览器。",
    },
    "cap": {
        "provider": "cap",
        "name": "Cap / @cap.js",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "redeem body / Cap token",
        "scope": "Cap v1 seeded PoW 与 format-2 sha256-pow：本地 SHA-256 nonce 搜索，可输出 /redeem body 或直接 redeem token；不启动浏览器。",
    },
    "chpiopow": {
        "provider": "chpiopow",
        "name": "chpio/pow-captcha",
        "category": "solver",
        "captcha_type": "target_match_pow",
        "status": "alpha",
        "output": "challenge solution body / redeemed token",
        "scope": "chpio/pow-captcha signed multi-challenge PoW：解析 signedData，复现 UTF-16LE SHA-256 签名与 SHA256(solution_le||nonce) target-bit 匹配，可提交 redeem；不启动浏览器。",
    },
    "impost": {
        "provider": "impost",
        "name": "Impost",
        "category": "solver",
        "captcha_type": "argon2id_pow",
        "status": "alpha",
        "output": "{challenge, nonce} / validated message",
        "scope": "Impost Zig/WASM Argon2id PoW：复现 t=3、m=8192KiB、p=1 的 Argon2id，支持 leading_zeroes 与 target_number 两种策略，输出 challenge salt + nonce；不启动浏览器。",
    },
    "kerberus": {
        "provider": "kerberus",
        "name": "Kerberus",
        "category": "solver",
        "captcha_type": "u128_score_pow",
        "status": "alpha",
        "output": "Solution{id, nonces} / validated token",
        "scope": "Kerberus 多盐 u128-score PoW：对每个 salt 预计算 SHA256(salt+serializedInput)，再搜索 SHA256(prefixHash||nonce_dec) 前 16 字节评分超过阈值，输出 nonces；不启动浏览器。",
    },
    "mcaptcha": {
        "provider": "mcaptcha",
        "name": "mCaptcha",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "verify body / mCaptcha token",
        "scope": "mCaptcha SHA-256 PoW：获取 /api/v1/pow/config，复现 bincode(String)+u128 score nonce 搜索，可提交 /verify 换 token；不启动浏览器。",
    },
    "paulpow": {
        "provider": "paulpow",
        "name": "PaulDotSH/pow-captcha",
        "category": "solver",
        "captcha_type": "bcrypt_pow",
        "status": "alpha",
        "output": "CaptchaServerInfo JSON / validated token",
        "scope": "PaulDotSH pow-captcha bcrypt PoW：复现 exact 与 prefix 两种 bcrypt 校验；exact 用 bcrypt verify 反查小范围 nonce，prefix 用 salt 前 16 字节构造 bcrypt salt 后匹配 hash 前缀；不启动浏览器。",
    },
    "pcaptcha": {
        "provider": "pcaptcha",
        "name": "P-Captcha",
        "category": "solver",
        "captcha_type": "quadratic_residue_pow",
        "status": "alpha",
        "output": "answer / validated token flow",
        "scope": "P-Captcha QuadraticResidueProblem：解析 Woodall prime challenge，用模平方根直接求 answer，可提交 {id, answer}；不启动浏览器。",
    },
    "powcaptcha": {
        "provider": "powcaptcha",
        "name": "pow_captcha",
        "category": "solver",
        "captcha_type": "buffer_reconstruction_pow",
        "status": "alpha",
        "output": "answer buffer / verification body",
        "scope": "pow_captcha 二进制 buffer reconstruction PoW：解析 serialized quiz、按 uncertainty ranges 做 mixed-radix 搜索，输出命中 SHA-256 的 answer；不启动浏览器。",
    },
    "privatecaptcha": {
        "provider": "privatecaptcha",
        "name": "PrivateCaptcha",
        "category": "solver",
        "captcha_type": "compute_pow",
        "status": "alpha",
        "output": "private-captcha-solution payload",
        "scope": "PrivateCaptcha compute puzzle：解析 puzzle/signature payload，复现 blake2b-256 threshold 多解 PoW 与 solutions metadata，输出 widget response；不启动浏览器。",
    },
    "portcullis": {
        "provider": "portcullis",
        "name": "Portcullis",
        "category": "solver",
        "captcha_type": "argon2_pow",
        "status": "alpha",
        "output": "verify body / captcha_token",
        "scope": "Portcullis Argon2id + SHA-256 PoW：解析 signed challenge，先计算 Argon2id base hash，再搜索 SHA256(base||nonce_le) 前导零，可提交 /verify 换 token；不启动浏览器。",
    },
    "wicketkeeper": {
        "provider": "wicketkeeper",
        "name": "Wicketkeeper",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "hidden-input solution / success JWT",
        "scope": "Wicketkeeper EdDSA-JWT PoW：获取 /v0/challenge，计算 SHA256(challenge+nonce) 前导零，可提交 /v0/siteverify 换 success JWT；不启动浏览器。",
    },
    "geetest": {
        "provider": "geetest",
        "name": "GeeTest v4",
        "category": "solver",
        "captcha_type": "slider",
        "status": "alpha",
        "output": "pass_token/lot_number",
        "scope": "GeeTest v4 滑动：bg/slice 提取、CV 匹配、轨迹拖拽、validate 提取。",
    },
    "yidun": {
        "provider": "yidun",
        "name": "NetEase Yidun",
        "category": "solver",
        "captcha_type": "jigsaw",
        "status": "alpha",
        "output": "validate/token/zoneId",
        "scope": "网易易盾滑动拼图：bg/front 提取、OpenCV 缺口定位、轨迹拖拽。",
    },
    "turnstile": {
        "provider": "turnstile",
        "name": "Cloudflare Turnstile",
        "category": "flow_observer",
        "captcha_type": "token_widget",
        "status": "observer",
        "output": "widget token / artifacts",
        "scope": "嵌入式 widget 的 render/execute/callback/input token 采集与提交链路复盘。",
    },
    "hcaptcha": {
        "provider": "hcaptcha",
        "name": "hCaptcha",
        "category": "flow_observer",
        "captcha_type": "token_widget",
        "status": "observer",
        "output": "widget token / artifacts",
        "scope": "render 参数、Enterprise rqdata、callback/input token、网络现场采集；不承诺图片挑战求解。",
    },
    "recaptcha": {
        "provider": "recaptcha",
        "name": "reCAPTCHA / Enterprise",
        "category": "flow_observer",
        "captcha_type": "token_widget",
        "status": "observer",
        "output": "widget/execute token / artifacts",
        "scope": "render/execute/action/token/network artifact 采集；不承诺高风险交互挑战求解。",
    },
}

UNSUPPORTED_CAPABILITIES: list[dict[str, str]] = [
    {
        "captcha_type": "text_click",
        "name": "文字点选",
        "reason": "需要模型训练和样本闭环；OCR/混淆表 demo 不作为 SDK 能力。",
    },
    {
        "captcha_type": "semantic_image_select",
        "name": "语义选图",
        "reason": "需要通用视觉语义模型和站点样本；当前不承诺。",
    },
    {
        "captcha_type": "complex_drag_sort",
        "name": "复杂拖拽/排序",
        "reason": "规则和行为链路不稳定；只保留几何明确的滑块/拼图类。",
    },
]


def list_capabilities() -> dict[str, Any]:
    """Return the product capability boundary used by README and CLI."""

    matrix = deepcopy(CAPABILITY_MATRIX)
    solvers = [item for item in matrix.values() if item["category"] == "solver"]
    flow_observers = [item for item in matrix.values() if item["category"] == "flow_observer"]
    return {
        "schema_version": 1,
        "solvers": solvers,
        "flow_observers": flow_observers,
        "unsupported": deepcopy(UNSUPPORTED_CAPABILITIES),
    }
