from __future__ import annotations

from copy import deepcopy
from typing import Any


CAPABILITY_MATRIX: dict[str, dict[str, Any]] = {
    "tencent": {
        "provider": "tencent",
        "name": "Tencent Captcha",
        "category": "solver",
        "captcha_type": "slider",
        "status": "primary",
        "output": "ticket/randstr",
        "scope": "腾讯滑块：缺口识别 + 轨迹拖拽 + ticket/randstr 提取。",
    },
    "aliyun": {
        "provider": "aliyun",
        "name": "Aliyun Captcha",
        "category": "solver",
        "captcha_type": "slider",
        "status": "primary",
        "output": "verify_code/session artifacts",
        "scope": "阿里云滑块：站点 profile + CV 缺口 + 轨迹拖拽 + attempt/session retry。",
    },
    "ajcaptcha": {
        "provider": "ajcaptcha",
        "name": "AJ-Captcha / Anji",
        "category": "solver",
        "captcha_type": "slider_protocol",
        "status": "alpha",
        "output": "captchaVerification/token",
        "scope": "AJ-Captcha blockPuzzle：/captcha/get 图像缺口定位 + AES pointJson + /captcha/check 协议提交；不启动浏览器。",
    },
    "activehashcash": {
        "provider": "activehashcash",
        "name": "ActiveHashcash",
        "category": "solver",
        "captcha_type": "rails_hashcash_sha256",
        "status": "alpha",
        "output": "hashcash hidden field / validated response",
        "scope": "BaseSecrete/active_hashcash Rails 中间件 solver：解析 input[data-hashcash] 的 resource/bits/date，生成 rand，复现 Web Worker 的 SHA-256 Hashcash leading-zero bit counter 搜索，输出 hashcash hidden field；不启动浏览器。",
    },
    "altcha": {
        "provider": "altcha",
        "name": "ALTCHA",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "base64 payload / Authorization header",
        "scope": "ALTCHA v1/v2 PoW：v1 解析 challenge 或 WWW-Authenticate 反查 number；v2 复现 PBKDF2/SHA/Scrypt/Argon2id KDF challenge、HMAC 签名与 verify-compatible fast path，输出表单 payload 或 M2M Authorization header；不启动浏览器。",
    },
    "anubis": {
        "provider": "anubis",
        "name": "Anubis",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "pass-challenge params / auth cookie",
        "scope": "Anubis fast/slow PoW：解析页面或 make-challenge JSON，计算 SHA256(randomData+nonce) 前导零，生成 pass-challenge 参数，可提交换 cookie；不启动浏览器。",
    },
    "albireo": {
        "provider": "albireo",
        "name": "Albireo",
        "category": "solver",
        "captcha_type": "serverless_signed_pow",
        "status": "alpha",
        "output": "nonce/response form body / albireo_solved cookie",
        "scope": "Albireo serverless PoW：解析 HTML 与 albireo_challenge HMAC cookie，兼容 CF v2 的 difficulty/fp_nonce 绑定和 Netlify/Vercel v1，补真实浏览器请求头后复现 SHA256(challenge+nonce) leading-zero PoW 并 POST 表单换 albireo_solved；不启动浏览器。",
    },
    "powxy": {
        "provider": "powxy",
        "name": "Powxy",
        "category": "solver",
        "captcha_type": "reverse_proxy_pow",
        "status": "alpha",
        "output": "powxy form field / powxy HMAC cookie",
        "scope": "Powxy 反向代理 PoW：解析 challenge 页面 data-identifier/data-difficulty，保持 User-Agent/Accept-Encoding/Accept-Language 一致，复现 SHA256(identifier||uint64_le(nonce)) leading-zero-bit 搜索，POST base64 nonce 换 powxy cookie；不启动浏览器。",
    },
    "goaway": {
        "provider": "goaway",
        "name": "go-away js-pow-sha256",
        "category": "solver",
        "captcha_type": "goaway_js_pow_sha256",
        "status": "alpha",
        "output": "__goaway_token / go-away state cookie",
        "scope": "go-away WASM/JS PoW：解析 challenge 页面 script.mjs 与 Request Id，保持 IP/UA/Accept/CH headers 稳定，POST make-challenge 取得 challenge/target，复现 Worker 的 SHA256(challenge||uint64_le(nonce)) < target，GET verify-challenge 换 *-state cookie；不启动浏览器。",
    },
    "guardianwaf": {
        "provider": "guardianwaf",
        "name": "GuardianWAF JS Challenge",
        "category": "solver",
        "captcha_type": "unsigned_js_pow_hmac_cookie",
        "status": "alpha",
        "output": "__gwaf_challenge HMAC cookie / verify form body",
        "scope": "GuardianWAF JS PoW：解析 inline C/D/R challenge，复现 WebCrypto 的 SHA256(challenge+hex_nonce) 前导 bit 搜索，POST /__guardianwaf/challenge/verify 换 IP-bound HMAC cookie；支持未签名 challenge 的 direct mint 路径，不启动浏览器。",
    },
    "shapow": {
        "provider": "shapow",
        "name": "SHAPOW Nginx PoW",
        "category": "solver",
        "captcha_type": "nginx_ip_time_bound_pow",
        "status": "alpha",
        "output": "shapow-response query / IP whitelist",
        "scope": "SHAPOW Nginx 模块 PoW：解析 challenge-settings.js 中 IP+server_time+random_challenge 绑定的 serverData，复现 Worker 的 SHA256(serverData||nonce16_le_counter) leading-zero-bit 搜索，通过 shapow-response 查询参数回传并进入 IP whitelist；不启动浏览器。",
    },
    "auro": {
        "provider": "auro",
        "name": "Auro.Network",
        "category": "solver",
        "captcha_type": "encrypted_behavior_pow",
        "status": "alpha",
        "output": "validate body / Auro token",
        "scope": "Auro.Network AES-GCM 行为数据 + SHA-256 PoW：获取 enckey，生成鼠标轨迹并 AES-GCM 加密，提交 setup 拿 prefix/difficulty，搜索 nonce 后 validate；不启动浏览器。",
    },
    "awswaf": {
        "provider": "awswaf",
        "name": "AWS WAF Challenge",
        "category": "solver",
        "captcha_type": "encrypted_telemetry_scrypt_sha2_network_pow",
        "status": "prototype",
        "output": "verify/mp_verify payload core / aws-waf-token flow skeleton",
        "scope": "AWS WAF challenge.js 核心 solver：复现 CRC32 checksum + AES-256-GCM encrypted signals、NetworkBandwidth payload、SHA2/Scrypt hashcash PoW；当前先做 parser/fixture/core，不启动浏览器。",
    },
    "wargon2": {
        "provider": "wargon2",
        "name": "Wargon2 Captcha",
        "category": "solver",
        "captcha_type": "argon2id_prefix_pow_fingerprint",
        "status": "alpha",
        "output": "nonce/hash/fingerprint verify body",
        "scope": "femshift/wargon2-captcha 协议 solver：复现 WASM Argon2id(salt+nonce) 前缀 PoW，并合成反向 base64 + AES-GCM fingerprint，可提交 /api/v1/verify；不启动浏览器。",
    },
    "balooproxy": {
        "provider": "balooproxy",
        "name": "balooProxy / balooPow",
        "category": "solver",
        "captcha_type": "balooproxy_js_suffix_sha256_cookie",
        "status": "alpha",
        "output": "_2__bProxy_v cookie value",
        "scope": "balooProxy/balooPow JS suffix challenge：复现 accessKey+OTP 派生链路与 SHA256(publicSalt+suffix) 精确匹配，输出反向代理 clearance cookie；不启动浏览器。",
    },
    "basedflare": {
        "provider": "basedflare",
        "name": "BasedFlare / haproxy-protection",
        "category": "solver",
        "captcha_type": "haproxy_pow_cookie",
        "status": "alpha",
        "output": "_basedflare_pow cookie / pow_response",
        "scope": "BasedFlare HAProxy edge PoW：解析 /.basedflare/bot-check JSON/HTML challenge，复现 sha256/argon2 Worker PoW，POST pow_response 换 _basedflare_pow clearance cookie；不启动浏览器。",
    },
    "acwscv2": {
        "provider": "acwscv2",
        "name": "Aliyun / acw_sc__v2 JS Cookie",
        "category": "solver",
        "captcha_type": "aliyun_acw_sc_v2_js_cookie",
        "status": "alpha",
        "output": "acw_sc__v2 cookie",
        "scope": "阿里云/加速乐类 acw_sc__v2 JS challenge：解析 arg1、混淆 string table、RC4 key 与 40 位 shuffle，本地生成 clearance cookie 并可重试 protected page；不启动浏览器。",
    },
    "pingoo": {
        "provider": "pingoo",
        "name": "Pingoo Captcha",
        "category": "solver",
        "captcha_type": "jwt_cookie_sha256_pow",
        "status": "alpha",
        "output": "__pingoo_captcha_verified cookie / verify JSON body",
        "scope": "Pingoo 反向代理 CAPTCHA：GET /__pingoo/captcha/api/init 领取 EdDSA JWT challenge cookie，复现 SHA256(challenge+nonce) 十六进制前缀 PoW，POST /__pingoo/captcha/api/verify 换 __pingoo_captcha_verified JWT cookie；不启动浏览器。",
    },
    "akamai_bm": {
        "provider": "akamai_bm",
        "name": "Akamai Bot Manager",
        "category": "solver",
        "captcha_type": "akamai_bm_sensor_experimental",
        "status": "experimental",
        "output": "sensor_data / mn_r / _abck Set-Cookie",
        "scope": "Akamai BM experimental：从 bm_sz 提取 transform keys，复现 LCG string shift 与字段 shuffle，支持 minimal v3-style sensor JSON encode/decode 和 /_bm/_data mock submit；可解析 _abck 的 mn_* challenge 并复现 SHA-256 byte-wise modulo PoW 生成 mn_r；不启动浏览器，不宣称完整 _abck/reese 风控绕过。",
    },
    "arkose": {
        "provider": "arkose",
        "name": "Arkose Labs / FunCaptcha",
        "category": "solver",
        "captcha_type": "arkose_funcaptcha_bda_token",
        "status": "experimental",
        "output": "encrypted bda / session token primitive",
        "scope": "Arkose/FunCaptcha experimental：复现 public_key token 初始化所需的 browser data array(BDA) 结构、FingerprintJS x64 MurmurHash128、OpenSSL EVP_BytesToKey 风格 AES-256-CBC 加密与 /fc/gt2/public_key/{pkey} 表单提交，解析 token/session/sup 状态；不做视觉游戏自动答题，不宣称完整 FunCaptcha 绕过。",
    },
    "kasada_kpsdk": {
        "provider": "kasada_kpsdk",
        "name": "Kasada KPSDK",
        "category": "solver",
        "captcha_type": "kasada_kpsdk_headers_experimental",
        "status": "experimental",
        "output": "x-kpsdk-* headers / KPSDK:DONE primitive",
        "scope": "Kasada/KPSDK experimental：用 Node VM 补最小浏览器环境执行本地/显式获取的 p.js，触发受保护请求并捕获 x-kpsdk-* headers 与 KPSDK:DONE 消息；不启动浏览器，不宣称完整 Kasada 绕过。",
    },
    "datadome": {
        "provider": "datadome",
        "name": "DataDome JavaScript Tag",
        "category": "solver",
        "captcha_type": "datadome_js_tag_signals_experimental",
        "status": "experimental",
        "output": "JS signal request / datadome cookie primitive",
        "scope": "DataDome experimental：用 Node VM 补最小浏览器环境执行 tags.js，捕获 /js/ 信号请求、datadome cookie 写入，可选 replay 到受控 endpoint 验证 Set-Cookie/x-set-cookie；不启动浏览器，不宣称完整 DataDome 绕过。",
    },
    "perimeterx": {
        "provider": "perimeterx",
        "name": "PerimeterX / HUMAN PX",
        "category": "solver",
        "captcha_type": "perimeterx_px_sensor_experimental",
        "status": "experimental",
        "output": "PX collector request / _px cookies primitive",
        "scope": "PerimeterX/HUMAN PX experimental：用 Node VM 补最小浏览器环境执行 px.js/collector 脚本，捕获 /api/v*/collector、fetch/XHR/beacon/image 请求与 _px/_px2/_px3/_pxvid cookie；可选 replay 到受控 endpoint 验证 Set-Cookie；不启动浏览器，不宣称完整 PX 绕过。",
    },
    "vercel_botid": {
        "provider": "vercel_botid",
        "name": "Vercel BotID / X-Is-Human",
        "category": "solver",
        "captcha_type": "x_is_human_aes_gcm_fingerprint",
        "status": "prototype",
        "output": "X-Is-Human header JSON / submitted response",
        "scope": "Vercel BotID：从 BotID c.js/简化脚本或 JSON context 提取 key/seed/signature/version，合成低风险 WebGL/browser fingerprint，并复现 PBKDF2-SHA256 + AES-256-GCM 生成 X-Is-Human header；raw 混淆脚本可走 Node VM 最小浏览器环境补全并直接执行 V_C callback，不启动浏览器；可选向受保护接口提交 X-Is-Human/X-Path/X-Method 做协议闭环。",
    },
    "hcaptcha_hsw": {
        "provider": "hcaptcha_hsw",
        "name": "hCaptcha HSW",
        "category": "solver",
        "captcha_type": "hcaptcha_hsw_n_experimental",
        "status": "experimental",
        "output": "HSW n / proof primitive",
        "scope": "hCaptcha HSW experimental：用 Node VM 补最小浏览器/WebAssembly/WebCrypto 环境，执行本地或显式获取的 HSW JS/WASM glue，调用 hsw(req) 生成 n/proof；不启动浏览器，不做图像任务，不宣称完整 hCaptcha 绕过。",
    },
    "friendlycaptcha": {
        "provider": "friendlycaptcha",
        "name": "FriendlyCaptcha",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "frc-captcha-solution payload",
        "scope": "FriendlyCaptcha classic PoW：获取 puzzle，按 friendly-pow/blake2b 求解多段 nonce，输出隐藏表单字段 payload；不启动浏览器。",
    },
    "getpowcaptcha": {
        "provider": "getpowcaptcha",
        "name": "powCAPTCHA",
        "category": "solver",
        "captcha_type": "signals_bound_pow",
        "status": "prototype",
        "output": "powcaptcha-response solution token / verified response",
        "scope": "powCAPTCHA widget 协议：合成 fingerprint/signals 请求 /challenges/create，复现 SHA256(signature+problem+nonce) 多 problem 前导零 PoW，输出 btoa(JSON.stringify(solution)) 的 powcaptcha-response；不启动浏览器。",
    },
    "fcaptcha": {
        "provider": "fcaptcha",
        "name": "FCaptcha",
        "category": "solver",
        "captcha_type": "signals_bound_pow",
        "status": "alpha",
        "output": "verify body / FCaptcha token",
        "scope": "FCaptcha 行为/环境检测 + signalsHash 绑定 SHA-256 PoW：合成低风险 behavioral/environmental signals，按 JSON.stringify signalsHash 搜索 nonce，可提交 /api/verify 换 token；不启动浏览器。",
    },
    "gunslol": {
        "provider": "gunslol",
        "name": "guns.lol",
        "category": "solver",
        "captcha_type": "seal_pow_blake3",
        "status": "alpha",
        "output": "{seal, _oo} / validated token",
        "scope": "guns.lol _gs_sets seal PoW：解析 _2xa 空位模板，枚举十六进制 seal 使 SHA256(seal+_n+_org_ts)=o09，再生成 BLAKE3 _oo 标签；不启动浏览器。",
    },
    "h33botshield": {
        "provider": "h33botshield",
        "name": "H33 BotShield",
        "category": "solver",
        "captcha_type": "botshield_pow",
        "status": "alpha",
        "output": "h33_bot_token / session_token",
        "scope": "H33 BotShield：复现公开 widget 的 /v1/botshield/challenge + SHA256(nonce+counter) leading-zero-bit PoW + /v1/botshield/solve，保留 x-h33 post-quantum receipt headers；不启动浏览器。",
    },
    "hashguard": {
        "provider": "hashguard",
        "name": "HashGuard",
        "category": "solver",
        "captcha_type": "jwt_proof_pow",
        "status": "alpha",
        "output": "proofToken JWT / introspection result",
        "scope": "HashGuard PoW CAPTCHA：请求 /pow/challenges，复现 SHA256(challengeId:seed:nonce) <= target 的阈值搜索，提交 /pow/verifications 换 ES256/JWT proofToken，可选 /pow/assertions/introspect；不启动浏览器。",
    },
    "trustcaptcha": {
        "provider": "trustcaptcha",
        "name": "TrustCaptcha",
        "category": "solver",
        "captcha_type": "fingerprint_multi_pow",
        "status": "alpha",
        "output": "tc-verification-token / submit body",
        "scope": "TrustCaptcha v3：合成 widget/browserInformation/fingerprints/integrityHash，复现 worker 中 SHA256(input||'tcn'+counter) 多任务 PoW，提交 /v2/verifications/{id}/challenges 换 verificationToken；不启动浏览器。",
    },
    "stravcaptcha": {
        "provider": "stravcaptcha",
        "name": "@strav/captcha",
        "category": "solver",
        "captcha_type": "stateless_hmac_pow",
        "status": "alpha",
        "output": "_captcha/_captcha_answer submit body",
        "scope": "@strav/captcha stateless PoW：解析 HMAC-SHA256 签名 token 的公开 payload，提取 salt/difficulty，复现 SHA256(salt+':'+nonce) leading-zero PoW，生成 middleware 可验提交字段；不启动浏览器。",
    },
    "justnocaptcha": {
        "provider": "justnocaptcha",
        "name": "JustNoCaptcha",
        "category": "solver",
        "captcha_type": "multi_puzzle_fnv_pow",
        "status": "alpha",
        "output": "challenge/solution submit body",
        "scope": "JustNoCaptcha 多 puzzle PoW：解析 difficulty+puzzles+challengeHash，复现 JS FNV1a/fmix hashInt，逐 puzzle 搜索定长十进制 solution，可选 challengeSalt 校验 challenge 完整性；不启动浏览器。",
    },
    "capybara": {
        "provider": "capybara",
        "name": "Capybara-Captcha",
        "category": "solver",
        "captcha_type": "payload_bound_pow",
        "status": "alpha",
        "output": "{id, solution, payload_token} verify body",
        "scope": "Capybara-Captcha Worker 协议 solver：请求 /api/challenge 获取 id/nonce/difficulty/payload_token，复现 SHA256(nonce+solution) 十六进制前缀零 PoW，可选校验 payload_token 的 INSTANCE_ID+secret 签名并提交 /api/verify；不启动浏览器。",
    },
    "btx": {
        "provider": "btx",
        "name": "BTX MatMul Service Challenge",
        "category": "solver",
        "captcha_type": "matmul_service_pow",
        "status": "prototype",
        "output": "X-BTX proof headers / challenge proof JSON",
        "scope": "BTX service-challenge：复现 M31 有限域矩阵、noise rank、header sigma、block transcript SHA-256d 与 digest_le <= target 的 MatMul PoW；纯 Python 原型默认限制小/中维度，不启动浏览器。",
    },
    "botcha": {
        "provider": "botcha",
        "name": "BOTCHA",
        "category": "solver",
        "captcha_type": "ai_speed_challenge",
        "status": "alpha",
        "output": "answers / access_token / badge",
        "scope": "BOTCHA AI-agent challenge：GET /v1/token 或 /api/speed-challenge 下发 sha256_first8 任务，直接计算多题答案并 POST /v1/token/verify 换 JWT；兼容 /api/challenge prime+salt puzzle，不启动浏览器。",
    },
    "donatello": {
        "provider": "donatello",
        "name": "Donatello",
        "category": "solver",
        "captcha_type": "canvas_fingerprint_challenge",
        "status": "alpha",
        "output": "totalHash1 / totalHash2 / metrics2 / verified status",
        "scope": "Donatello canvas/subpixel challenge：GET / 领取 challenge_id，GET /challenge?id=... 下发 first_task/second_task，离线复现 chessboard+rectangle+line RGBA channel SHA-256 与 alpha metrics，POST /challenge；同时暴露 reference POST 未强校验 totalHash 的协议缺口，不启动浏览器。",
    },
    "vulcan": {
        "provider": "vulcan",
        "name": "EduVulcan / WASM-for-Vulcan",
        "category": "solver",
        "captcha_type": "chained_sha256_uint32_pow",
        "status": "alpha",
        "output": "captcha-response submit body",
        "scope": "EduVulcan 链式 SHA-256 uint32-target PoW：提取 data-challenge/data-difficulty/data-rounds，逐轮搜索 first decimal nonce，使 SHA256(base+nonce) 前 4 字节大端整数小于 difficulty，并把上一轮 nonce 追加进下一轮 base；不启动浏览器。",
    },
    "spow": {
        "provider": "spow",
        "name": "spow / leptos-captcha",
        "category": "solver",
        "captcha_type": "signed_hashcash_pow",
        "status": "alpha",
        "output": "pow submit body / validated response",
        "scope": "spow/leptos-captcha WASM PoW：解析 version:difficulty:expires:salt:signature challenge，复现 SHA256(challenge||counter) leading-zero bit 搜索，可选用服务端 secret 校验 challenge 签名并提交 hidden pow 字段；不启动浏览器。",
    },
    "cap": {
        "provider": "cap",
        "name": "Cap / @cap.js",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "redeem body / Cap token",
        "scope": "Cap v1 seeded PoW、format-2 sha256-pow/RSW 与 instrumentation payload：本地 nonce 搜索、顺序 modular squaring；自持 secret 或显式 instr 时可构造 verifier-ready instrumentation，不启动浏览器。",
    },
    "cryptopuzzle": {
        "provider": "cryptopuzzle",
        "name": "crypto-puzzle",
        "category": "solver",
        "captcha_type": "rsw_time_lock_puzzle",
        "status": "alpha",
        "output": "decrypted message/token",
        "scope": "crypto-puzzle RSW time-lock puzzle：解析 archive，复现顺序 repeated-squaring 解出 AES-GCM/PBKDF2 secret，恢复 message/token；不启动浏览器。",
    },
    "captxa": {
        "provider": "captxa",
        "name": "Captxa",
        "category": "solver",
        "captcha_type": "ja4_bound_pow",
        "status": "alpha",
        "output": "solve body / X-Captcha-Token",
        "scope": "Captxa simple mode：补 browser metrics 通过环境预检，解析 opaque challenge_token 与 pow_challenge，复现 SHA256(pow32||nonce_le64) leading-zero PoW，可提交 /solve/simp；不启动浏览器。",
    },
    "crovly": {
        "provider": "crovly",
        "name": "Crovly",
        "category": "solver",
        "captcha_type": "fingerprint_behavior_pow",
        "status": "alpha",
        "output": "verify body / Crovly token",
        "scope": "Crovly widget 协议 solver：复现 SHA256(nonce+counter) 前导 bit PoW，合成 fingerprintHash、environment 与行为统计，按 X-Site-Key 提交 /verify 换 token；不启动浏览器。",
    },
    "chpiopow": {
        "provider": "chpiopow",
        "name": "chpio/pow-captcha",
        "category": "solver",
        "captcha_type": "target_match_pow",
        "status": "alpha",
        "output": "challenge solution body / redeemed token",
        "scope": "chpio/pow-captcha signed multi-challenge PoW：解析 signedData，复现 UTF-16LE SHA-256 签名与 SHA256(solution_le||nonce) target-bit 匹配，可提交 redeem；不启动浏览器。",
    },
    "impost": {
        "provider": "impost",
        "name": "Impost",
        "category": "solver",
        "captcha_type": "argon2id_pow",
        "status": "alpha",
        "output": "{challenge, nonce} / validated message",
        "scope": "Impost Zig/WASM Argon2id PoW：复现 t=3、m=8192KiB、p=1 的 Argon2id，支持 leading_zeroes 与 target_number 两种策略，输出 challenge salt + nonce；不启动浏览器。",
    },
    "kerberus": {
        "provider": "kerberus",
        "name": "Kerberus",
        "category": "solver",
        "captcha_type": "u128_score_pow",
        "status": "alpha",
        "output": "Solution{id, nonces} / validated token",
        "scope": "Kerberus 多盐 u128-score PoW：对每个 salt 预计算 SHA256(salt+serializedInput)，再搜索 SHA256(prefixHash||nonce_dec) 前 16 字节评分超过阈值，输出 nonces；不启动浏览器。",
    },
    "lapti": {
        "provider": "lapti",
        "name": "Lapti Proof-of-Work Captcha",
        "category": "solver",
        "captcha_type": "sha3_token_pow",
        "status": "alpha",
        "output": "data+nonce / protected action result",
        "scope": "Lapti PoW：请求 /handshake/{data} 获取 SHA3-512(data+SECRET) token 与 complexity，复现 worker 中 SHA3-512(token+nonce) 前 complexity 个字节为 0 的搜索，可提交 /action/{data}/{nonce}；不启动浏览器。",
    },
    "mcaptcha": {
        "provider": "mcaptcha",
        "name": "mCaptcha",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "verify body / mCaptcha token",
        "scope": "mCaptcha SHA-256 PoW：获取 /api/v1/pow/config，复现 bincode(String)+u128 score nonce 搜索，可提交 /verify 换 token；不启动浏览器。",
    },
    "neoirc": {
        "provider": "neoirc",
        "name": "NeoIRC Hashcash",
        "category": "solver",
        "captcha_type": "resource_body_bound_hashcash",
        "status": "alpha",
        "output": "pow_token / hashcash meta / session token",
        "scope": "NeoIRC Hashcash：复现 WebCrypto 的 6 字段 SHA-256 Hashcash，支持 session 级 resource 绑定 stamp 和 channel PRIVMSG 的 channel+bodyHash 绑定 stamp，可提交 /api/v1/session；不启动浏览器。",
    },
    "hashptcha": {
        "provider": "hashptcha",
        "name": "Hashptcha",
        "category": "solver",
        "captcha_type": "prefix_hash_cracking_task",
        "status": "alpha",
        "output": "token/value/secret_key verify body",
        "scope": "Hashptcha 分布式 hash-cracking CAPTCHA：复现 iframe 的 byte-aligned binary start_point 递增、MD5/SHA256(raw bytes) 二进制 digest 前缀 target 匹配，输出 token+value，可提交 /verify；不启动浏览器。",
    },
    "paulpow": {
        "provider": "paulpow",
        "name": "PaulDotSH/pow-captcha",
        "category": "solver",
        "captcha_type": "bcrypt_pow",
        "status": "alpha",
        "output": "CaptchaServerInfo JSON / validated token",
        "scope": "PaulDotSH pow-captcha bcrypt PoW：复现 exact 与 prefix 两种 bcrypt 校验；exact 用 bcrypt verify 反查小范围 nonce，prefix 用 salt 前 16 字节构造 bcrypt salt 后匹配 hash 前缀；不启动浏览器。",
    },
    "pcaptcha": {
        "provider": "pcaptcha",
        "name": "P-Captcha",
        "category": "solver",
        "captcha_type": "quadratic_residue_pow",
        "status": "alpha",
        "output": "answer / validated token flow",
        "scope": "P-Captcha QuadraticResidueProblem：解析 Woodall prime challenge，用模平方根直接求 answer，可提交 {id, answer}；不启动浏览器。",
    },
    "phpantiddos": {
        "provider": "phpantiddos",
        "name": "php-anti-ddos PoW Gate",
        "category": "solver",
        "captcha_type": "stateless_hmac_multi_pow_cookie",
        "status": "alpha",
        "output": "pow_nonces form body / __pow_token cookie",
        "scope": "thblfr/php-anti-ddos L7 PoW：解析无 session 的 HMAC 签名 challenge，绑定 host+SHA256(IP|UA)+N/K，复现多子挑战 SHA256(challenge:i:nonce) 前导 bit 搜索，POST 表单换 __pow_token；不启动浏览器。",
    },
    "powcaptcha": {
        "provider": "powcaptcha",
        "name": "pow_captcha",
        "category": "solver",
        "captcha_type": "buffer_reconstruction_pow",
        "status": "alpha",
        "output": "answer buffer / verification body",
        "scope": "pow_captcha 二进制 buffer reconstruction PoW：解析 serialized quiz、按 uncertainty ranges 做 mixed-radix 搜索，输出命中 SHA-256 的 answer；不启动浏览器。",
    },
    "powbot": {
        "provider": "powbot",
        "name": "PoW Bot Deterrent",
        "category": "solver",
        "captcha_type": "scrypt_pow",
        "status": "alpha",
        "output": "nonce / validated OK",
        "scope": "sequentialread/PoW Bot Deterrent scrypt-WASM 协议 solver：解析 base64 JSON challenge，复现 scrypt(nonce_bytes,preimage_bytes,N/r/p/klen) 尾部阈值比较，可提交 /Verify；不启动浏览器。",
    },
    "powchallenge": {
        "provider": "powchallenge",
        "name": "POWChallenge / powchallenge-server",
        "category": "solver",
        "captcha_type": "argon2id_memory_pow",
        "status": "alpha",
        "output": "verify body / validated message",
        "scope": "powchallenge-server Argon2id memory-hard PoW：解析 GET /challenge 的 req_id+challenge+difficulty，复现 t=1,m=19456KiB,p=1 的 Argon2id 前导零 bit，输出 /verify body；不启动浏览器。",
    },
    "powforge": {
        "provider": "powforge",
        "name": "PowForge CAPTCHA",
        "category": "solver",
        "captcha_type": "signed_sha256_pow_token",
        "status": "alpha",
        "output": "pf_token / validated token",
        "scope": "PowForge CAPTCHA 协议 solver：获取 /api/challenge 的 salt/difficulty/signature/id，复现 worker 的 SHA256(salt+nonce) leading-zero bit 搜索，提交 /api/verify 换 signed token，可选 /api/token/verify；不启动浏览器。",
    },
    "powreaction": {
        "provider": "powreaction",
        "name": "pow-reaction",
        "category": "solver",
        "captcha_type": "signed_multi_round_pow",
        "status": "alpha",
        "output": "{challenge, solutions, reaction} / success",
        "scope": "pow-reaction JWT 签名多轮 PoW：解析 HS256 JWT challenge，按 rounds 复现 SHA256(round+'.'+nonce) 前导零 bit，可提交 reactions endpoint，支持 clientId/context 绑定与 redeem 防重放链路；不启动浏览器。",
    },
    "procaptcha": {
        "provider": "procaptcha",
        "name": "Prosopo Procaptcha PoW",
        "category": "solver",
        "captcha_type": "prosopo_pow",
        "status": "alpha",
        "output": "pow solution body / verified response",
        "scope": "Prosopo Procaptcha PoW：复现 @prosopo/util 的 SHA256(nonce+challenge) 前导十六进制零搜索，支持 provider challenge 拉取与 signed timestamp submit body；不启动浏览器。",
    },
    "tollbooth": {
        "provider": "tollbooth",
        "name": "Tollbooth / libcaptcha",
        "category": "solver",
        "captcha_type": "tollbooth_protocol",
        "status": "alpha",
        "output": "verify form / clearance token",
        "scope": "Tollbooth 协议 solver：解析 JSON/HTML challenge，复现 SHA-256 与 SHA256-Balloon memory-hard PoW，并支持 navigator-attestation HTTP poll 的稀疏 signals token flow；不启动浏览器。",
    },
    "privatecaptcha": {
        "provider": "privatecaptcha",
        "name": "PrivateCaptcha",
        "category": "solver",
        "captcha_type": "compute_pow",
        "status": "alpha",
        "output": "private-captcha-solution payload",
        "scope": "PrivateCaptcha compute puzzle：解析 puzzle/signature payload，复现 blake2b-256 threshold 多解 PoW 与 solutions metadata，输出 widget response；不启动浏览器。",
    },
    "portcullis": {
        "provider": "portcullis",
        "name": "Portcullis",
        "category": "solver",
        "captcha_type": "argon2_pow",
        "status": "alpha",
        "output": "verify body / captcha_token",
        "scope": "Portcullis Argon2id + SHA-256 PoW：解析 signed challenge，先计算 Argon2id base hash，再搜索 SHA256(base||nonce_le) 前导零，可提交 /verify 换 token；不启动浏览器。",
    },
    "swetrix": {
        "provider": "swetrix",
        "name": "Swetrix CAPTCHA",
        "category": "solver",
        "captcha_type": "swetrix_pow",
        "status": "alpha",
        "output": "verify body / Swetrix token",
        "scope": "Swetrix CAPTCHA：解析 /generate 的 challenge+difficulty，复现 SHA256(challenge+':'+nonce) 前导十六进制零 PoW，可提交 /verify 并可选 /validate；不启动浏览器。",
    },
    "wicketkeeper": {
        "provider": "wicketkeeper",
        "name": "Wicketkeeper",
        "category": "solver",
        "captcha_type": "proof_of_work",
        "status": "alpha",
        "output": "hidden-input solution / success JWT",
        "scope": "Wicketkeeper EdDSA-JWT PoW：获取 /v0/challenge，计算 SHA256(challenge+nonce) 前导零，可提交 /v0/siteverify 换 success JWT；不启动浏览器。",
    },
    "yourcaptcha": {
        "provider": "yourcaptcha",
        "name": "yourcaptcha",
        "category": "solver",
        "captcha_type": "behavior_pow",
        "status": "alpha",
        "output": "captcha payload / verified result",
        "scope": "yourcaptcha 行为 signals + HMAC challenge + SHA-256 exact PoW：合成低风险 telemetry 获取低 maxnumber，搜索 salt+number exact hash，可提交 verify；不启动浏览器。",
    },
    "silentchallenge": {
        "provider": "silentchallenge",
        "name": "silent-challenge",
        "category": "solver",
        "captcha_type": "passive_pow",
        "status": "alpha",
        "output": "challenge verify body / signed token",
        "scope": "silent-challenge motion/navigator attestation + SHA-256 balloon PoW：合成高分 motion 与 navigator signals，复现 memory-hard balloon hash 搜索 nonce，可提交 /challenge/:id/verify；不启动浏览器。",
    },
    "geetest": {
        "provider": "geetest",
        "name": "GeeTest v4",
        "category": "solver",
        "captcha_type": "slider",
        "status": "alpha",
        "output": "pass_token/lot_number",
        "scope": "GeeTest v4 滑动：bg/slice 提取、CV 匹配、轨迹拖拽、validate 提取。",
    },
    "yidun": {
        "provider": "yidun",
        "name": "NetEase Yidun",
        "category": "solver",
        "captcha_type": "jigsaw",
        "status": "alpha",
        "output": "validate/token/zoneId",
        "scope": "网易易盾滑动拼图：bg/front 提取、OpenCV 缺口定位、轨迹拖拽。",
    },
    "turnstile": {
        "provider": "turnstile",
        "name": "Cloudflare Turnstile",
        "category": "flow_observer",
        "captcha_type": "token_widget",
        "status": "observer",
        "output": "widget token / artifacts",
        "scope": "嵌入式 widget 的 render/execute/callback/input token 采集与提交链路复盘。",
    },
    "hcaptcha": {
        "provider": "hcaptcha",
        "name": "hCaptcha",
        "category": "flow_observer",
        "captcha_type": "token_widget",
        "status": "observer",
        "output": "widget token / artifacts",
        "scope": "render 参数、Enterprise rqdata、callback/input token、网络现场采集；不承诺图片挑战求解。",
    },
    "recaptcha": {
        "provider": "recaptcha",
        "name": "reCAPTCHA / Enterprise",
        "category": "flow_observer",
        "captcha_type": "token_widget",
        "status": "observer",
        "output": "widget/execute token / artifacts",
        "scope": "render/execute/action/token/network artifact 采集；不承诺高风险交互挑战求解。",
    },
}

UNSUPPORTED_CAPABILITIES: list[dict[str, str]] = [
    {
        "captcha_type": "text_click",
        "name": "文字点选",
        "reason": "需要模型训练和样本闭环；OCR/混淆表 demo 不作为 SDK 能力。",
    },
    {
        "captcha_type": "semantic_image_select",
        "name": "语义选图",
        "reason": "需要通用视觉语义模型和站点样本；当前不承诺。",
    },
    {
        "captcha_type": "complex_drag_sort",
        "name": "复杂拖拽/排序",
        "reason": "规则和行为链路不稳定；只保留几何明确的滑块/拼图类。",
    },
]


def list_capabilities() -> dict[str, Any]:
    """Return the product capability boundary used by README and CLI."""

    matrix = deepcopy(CAPABILITY_MATRIX)
    solvers = [item for item in matrix.values() if item["category"] == "solver"]
    flow_observers = [item for item in matrix.values() if item["category"] == "flow_observer"]
    return {
        "schema_version": 1,
        "solvers": solvers,
        "flow_observers": flow_observers,
        "unsupported": deepcopy(UNSUPPORTED_CAPABILITIES),
    }
